# Archivo: setup_gfs2.yml
---
- hosts: storage_nodes
  become: yes
  vars:
    cluster_name: "uma_cluster73-171" # SS-XXX a partir de target01
    hacluster_password: "haclusterPass" # Cambia esto
    shared_device: "/dev/disk/by-id/scsi-36001405d84a209e5fb1414196559eb4d" # Ejecuta ls /dev/disk/by-id/ en un nodo storage y copia uno de los iscsi que salga. Todos apunta al mismo sitio /dev/sdc
    fs_name: "san_storage73-171"
    mount_path: "/mnt/gfs2_storage"
    cluster_nodes: "192.168.173.172 192.168.173.173 192.168.173.174"
  tasks:
    - name: Preparar el entorno (DLM y Carpetas)
      shell: |
        modprobe dlm
        echo "dlm" > /etc/modules-load.d/dlm.conf
        mkdir -p {{ mount_path }} /etc/dlm
        # Este flag es crítico para evitar conflicto de DLM con Pacemaker
        echo "enable_fencing=0" > /etc/dlm/dlm.conf
      run_once: false
    - name: Iniciar pcsd y configurar password
      shell: |
        systemctl enable --now pcsd
        echo "{{ hacluster_password }}" | passwd --stdin hacluster
    - name: Configurar Cluster
      shell: |
        pcs host auth {{ cluster_nodes }} -u hacluster -p {{ hacluster_password }}
        pcs cluster setup {{ cluster_name }} {{ cluster_nodes }} --force
        pcs cluster start --all --wait
        pcs cluster enable --all
      run_once: true
    - name: Configurar Fencing (Agente Kdump)
      shell: |
        pcs property set stonith-enabled=false
        pcs stonith create lab_fence fence_kdump
        pcs property set stonith-enabled=true
        pcs property set no-quorum-policy=freeze
      run_once: true
    - name: Formatear GFS2 (Solo si no existe)
      shell: "mkfs.gfs2 -O -p lock_dlm -t {{ cluster_name }}:{{ fs_name }} -j 3 {{
        shared_device }}"
      when: inventory_hostname == groups['storage_nodes'][0]
      run_once: true
    - name: Crear Recursos y Restricciones
      shell: |
        pcs resource create dlm ocf:pacemaker:controld op monitor interval=30s clone interleave=true
        pcs resource create cluster_fs ocf:heartbeat:Filesystem \
         device="{{ shared_device }}" directory="{{ mount_path }}" fstype="gfs2" \
          options="noatime" op monitor interval=20s clone interleave=true
        pcs constraint order start dlm-clone then cluster_fs-clone
        pcs constraint colocation add cluster_fs-clone with dlm-clone
      run_once: true
    - name: Limpieza final
      command: "pcs resource cleanup"
      run_once: true
